# Generated by Django 4.2.1 on 2023-06-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nome')),
                ('surname', models.CharField(max_length=20, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=254)),
                ('hasValidEmail', models.BooleanField(default=False)),
                ('role', models.IntegerField(choices=[(0, 'Primeiro Acesso'), (1, 'Administrador'), (2, 'Funcionário'), (3, 'Suspenso')], default=0, verbose_name='Permissões')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
    ]
