# Generated by Django 4.2.1 on 2023-05-31 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_capacity_room_hasairconditioner_room_hasfan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Disponivel'),
        ),
        migrations.AddField(
            model_name='room',
            name='note',
            field=models.CharField(default='qualquer coisa', max_length=100, verbose_name='Observações'),
            preserve_default=False,
        ),
    ]
