# Generated by Django 4.2.1 on 2023-05-31 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_available_room_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Observações'),
        ),
    ]
