# Generated by Django 4.2.1 on 2023-06-17 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_alter_course_shift'),
        ('professors', '0001_initial'),
        ('rooms', '0005_alter_room_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.TimeField(verbose_name='Horário de Início')),
                ('endTime', models.TimeField(verbose_name='Horário de Término')),
                ('day', models.IntegerField(choices=[(1, 'Segunda'), (2, 'Terça'), (3, 'Quarta'), (4, 'Quinta'), (5, 'Sexta'), (6, 'Sábado')], default=1, verbose_name='Dia da Semana')),
                ('professorsId', models.ManyToManyField(to='professors.professor', verbose_name='Professor(es)')),
                ('roomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room', verbose_name='Sala')),
                ('subjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject', verbose_name='Disciplina')),
            ],
        ),
    ]
