# Generated by Django 4.2.1 on 2023-05-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Curso')),
                ('shift', models.IntegerField(choices=[(1, 'Manhã'), (2, 'Tarde'), (3, 'Noite')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Nome')),
                ('code', models.CharField(max_length=25, verbose_name='Código')),
                ('workload', models.IntegerField(verbose_name='Carga Horária')),
                ('group', models.CharField(max_length=2, verbose_name='Grupo')),
                ('coursesIds', models.ManyToManyField(blank=True, null=True, to='courses.course', verbose_name='Curso(s)')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='subjectsIds',
            field=models.ManyToManyField(blank=True, null=True, related_name='coursesId', to='courses.subject', verbose_name='Disciplinas'),
        ),
    ]
