# Generated by Django 4.2.1 on 2023-05-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='shift',
            field=models.IntegerField(choices=[(1, 'Manhã'), (2, 'Tarde'), (3, 'Noite')], default=1, verbose_name='Turno'),
        ),
    ]
